include:
  - project: 'decort.tech-infra/infrastructure/terraform/templates'
    file: '/terraform.gitlab-ci.yml'

.secrets:
  secrets:
    AWS_ACCESS_KEY_ID_FILE:
      vault: infrastructure/aws/AWS_ACCESS_KEY_ID@kv
    AWS_SECRET_ACCESS_KEY_FILE:
      vault: infrastructure/aws/AWS_SECRET_ACCESS_KEY@kv
    AWS_REGION_FILE:
      vault: infrastructure/aws/AWS_REGION@kv
    GITLAB_TOKEN_FILE:
      vault: infrastructure/gitlab/GITLAB_TOKEN@kv

before_script:
  - apk add --update vault libcap
  - setcap cap_ipc_lock= /usr/sbin/vault
  - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=devops jwt=$CI_JOB_JWT)"
  - export AWS_ACCESS_KEY_ID=$(cat $AWS_ACCESS_KEY_ID_FILE)
  - echo $AWS_ACCESS_KEY_ID_FILE
  - export AWS_SECRET_ACCESS_KEY=$(cat $AWS_SECRET_ACCESS_KEY_FILE)
  - export AWS_REGION=$(cat $AWS_REGION_FILE)
  - export GITLAB_TOKEN=$(cat $GITLAB_TOKEN_FILE)
